"""Turn the researched professions into trade profiles.

    python tools/build_profiles.py --dry-run
    python tools/build_profiles.py

WHY A GENERATOR AND NOT A HUNDRED HAND-WRITTEN FILES. The shape of a profile is
identical across trades -- thresholds, boosts, negation, recency, the request
language -- and only two parts differ: what the work is called, and how people
describe it going wrong. Writing that shape a hundred times by hand guarantees a
hundred subtly different files and no way to fix them all at once. So the shape
lives here, the content lives in research/, and a profile is what happens when
you put them together.

A regenerated profile does NOT overwrite a hand-tuned one: profiles are written
only where the file does not exist or was itself generated (it carries a marker).
The user's own tuning lives in `*.local.yaml` sidecars regardless.

SOURCES
    research/PROFESSIONS-100.md   the professions, their categories and urgency
    research/TRADE-VOCABULARY.md  per-trade subject nouns and problem phrases
Both are written by research and are the record of where this came from.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESEARCH = ROOT.parent / "research"
PROFILES = ROOT / "profiles"

MARKER = "# generated by tools/build_profiles.py"

#: Research slug -> a profile that already exists under a different name. The
#: four originals were written and tuned by hand against live scans, and they
#: are better than anything this generator produces; generating a near-duplicate
#: beside them would put two of the same trade in the dropdown and split the
#: tuning between them.
ALIASES = {
    "plumber": "plumbing",
    "wedding-photographer": "wedding-photography",
    "computer-repair-technician": "it-support",
}

#: How fast a lead goes cold, by how urgent the work is. A burst pipe found six
#: hours late is somebody else's job already; a wedding photographer booked for
#: next June is not.
HALF_LIFE = {"emergency": 12, "soon": 48, "planned": 168}


def professions(path: Path) -> list[dict]:
    """Parse the ranked table out of the research document."""
    rows: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not re.match(r"^\|\s*\d+\s*\|", line):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 10:
            continue
        rows.append({
            "rank": int(cells[0]),
            "slug": cells[1].strip("`"),
            "display_name": cells[2],
            "category": cells[3],
            "reach": cells[4],
            "frequency": cells[5],
            "urgency": cells[7],
            "also_called": [a.strip() for a in cells[8].split(",") if a.strip()],
        })
    return rows


def vocabulary(path: Path) -> dict[str, dict]:
    """Parse `## <slug>` sections with `subject:` and `problem:` bullet lists.

    A term flagged `# BROAD` by the research is recorded as broad rather than
    dropped. Those flags are the most valuable thing in the document: "garage",
    "range" and "window" are real words for real trades and also the words that
    made a plumbing emergency match auto-mechanic, and a job advert match
    appliance repair on "salary range". See render().
    """
    if not path.exists():
        return {}
    found: dict[str, dict[str, list[str]]] = {}
    slug, bucket = None, None
    for line in path.read_text(encoding="utf-8").splitlines():
        heading = re.match(r"^#{2,4}\s+`?([a-z0-9-]+)`?\s*$", line)
        if heading:
            slug, bucket = heading.group(1), None
            found.setdefault(slug, {"subject": [], "problem": [], "broad": set()})
            continue
        if slug is None:
            continue
        key = re.match(r"^\s*(subject|problem)\s*:\s*$", line, re.I)
        if key:
            bucket = key.group(1).lower()
            continue
        term = re.match(r"^\s*[-*]\s+(.+?)\s*$", line)
        if term and bucket:
            raw_line = term.group(1)
            broad = "BROAD" in raw_line.upper()
            value = raw_line.strip()
            # Research notes ride along with the phrase and are not part of it:
            # a "# BROAD - also general-contractor" flag on "punch list" made the
            # line 45 characters long, so the length guard dropped the term
            # entirely and the flag silently cost us the phrase it was warning
            # about. Strip the note, keep the phrase, keep the warning in the
            # document where a person reads it.
            value = value.split("#", 1)[0].strip()
            value = re.sub(r"\s*[\(\[].*?[\)\]]\s*$", "", value).strip()
            value = value.strip('"').strip("'")
            if value and len(value) < 40:
                found[slug][bucket].append(value.lower())
                if broad:
                    found[slug]["broad"].add(value.lower())
    return {s: v for s, v in found.items() if v["subject"] or v["problem"]}


#: A term claimed by this many trades or more cannot carry a match by itself.
#: Two is the honest bar: if two trades both call a word their own, that word
#: cannot tell them apart, and something else in the post has to. 90 of about
#: 4,000 phrases fall here. The research flags what it notices; this catches
#: what it does not -- "garage" is a room to a home organiser and a workshop to
#: a mechanic, which is how a burst pipe matched a car mechanic.
#:
#: A trade's own NAMES count as claims too, which is the only reason the garage
#: case is caught at all.
SHARED_ACROSS = 2

#: Ordinary English words that are also somebody's trade term. Each one is here
#: because it carried a match it had no business carrying, or is one word away
#: from doing so: "frame" made a door frame an auto-body lead, "branch" made
#: "Farmers Branch" a tree service lead, "range" made "salary range 70-90k" an
#: appliance repair lead.
#:
#: They are demoted, not deleted -- "frame" still counts towards an auto-body
#: match when something else in the post agrees with it. Trade words with only
#: one meaning ("toilet", "alternator", "shingle") are deliberately absent: a
#: blanket rule against single words would have cost every one of them.
AMBIGUOUS_WORDS = {
    "frame", "branch", "branches", "range", "unit", "units", "board", "line",
    "lines", "area", "model", "service", "work", "project", "space", "room",
    "light", "lights", "box", "block", "panel", "plate", "chain", "belt",
    "stand", "head", "seal", "level", "patch", "finish", "trim", "screen",
    "base", "top", "case", "cover", "part", "parts", "job", "jobs", "piece",
    "set", "system", "machine", "tool", "tools", "material", "materials",
    "plug",     # a tire plug, and the name of a Dallas Facebook group
}


def shared_terms(vocab: dict, rows: list[dict] | None = None) -> set[str]:
    """Terms too many trades claim for any one of them to own."""
    counts: dict[str, int] = {}
    for entry in vocab.values():
        for term in set(entry.get("subject") or []):
            counts[term] = counts.get(term, 0) + 1
    for row in rows or []:
        names = {row["display_name"].lower()} | {a.lower() for a in row["also_called"]}
        for term in names:
            counts[term] = counts.get(term, 0) + 1
    return ({term for term, n in counts.items() if n >= SHARED_ACROSS}
            | set(AMBIGUOUS_WORDS))


def claimed_by_hand_written(directory: Path) -> dict[str, int]:
    """What the hand-tuned profiles claim, so the generated ones defer to them.

    Without this the count is blind to the four originals: "heater" is HVAC's
    word and also plumbing's, but plumbing is hand-written, so HVAC looked like
    its only owner and kept it at full weight -- and "Water heater flooding the
    garage" came back as an HVAC lead.
    """
    import yaml
    counts: dict[str, int] = {}
    for path in sorted(directory.glob("*.yaml")):
        if path.name.startswith("_"):
            continue
        text = path.read_text(encoding="utf-8")
        if MARKER in text:
            continue                      # generated; already counted
        try:
            data = yaml.safe_load(text) or {}
        except Exception:
            continue
        for group in data.get("subject") or []:
            terms = group.get("terms", []) if isinstance(group, dict) else group
            for term in (terms if isinstance(terms, list) else [terms]):
                key = str(term).strip().lower()
                counts[key] = counts.get(key, 0) + 1
    return counts


#: The shapes a request takes, filled in with whatever the trade is called.
#: Every one of these is a real form from the shared asking research; what
#: changes per trade is only the blank. Six phrasings built from a single name
#: left 97 trades unable to search for their own customers -- a tree service
#: cannot find "need a stump ground" by asking Facebook for "tree service".
ASK_SHAPES = [
    "need {a} {name}", "looking for {a} {name}", "anyone know {a} good {name}",
    "{name} recommendations", "good {name} near me", "best {name}",
    "{name} needed", "who does {name}", "iso {name}",
]

#: Asking without naming the trade, which is how most people ask. Plumbing was
#: hand-written with exactly these shapes -- "water heater replaced", "who can
#: fix my" -- and they find the customers who describe the job instead of the
#: profession. A tree service will never be found by somebody typing "I need
#: someone to take down a dead oak".
JOB_SHAPES = ["who can fix my {thing}", "{thing} repair", "need my {thing} fixed",
              "{thing} replacement"]

#: Trades where the customer's noun is a thing that breaks. Everywhere else the
#: repair shapes are nonsense -- "who can fix my poodle" was generated for a dog
#: groomer before this existed -- so those trades ask for help instead.
REPAIR_CATEGORIES = {"home-trade", "vehicle"}

#: Somebody advertising themselves, in the first person. This has to be written
#: per trade: "i'm a" on its own would throw away "I'm a homeowner and I need a
#: plumber". A live Dallas scan returned "Hi I am a mobile mechanic with great
#: prices, call out fee $50" as a lead, twice.
OFFER_SHAPES = ["i'm a {name}", "i am a {name}", "im a {name}",
                "i'm your {name}", "as a {name}"]
HELP_SHAPES = ["need help with my {thing}", "help with my {thing}",
               "someone for my {thing}"]

#: How many phrasings a trade gets. A continuous session rotates six per pass,
#: so this is three passes of genuinely different questions.
MAX_ASKS = 18


def ask_phrases(names: list[str], things: list[str], problems: list[str],
                urgency: str, category: str = "") -> list[str]:
    """Every way a customer might ask for this trade, broadest coverage first.

    Built in rounds rather than in order, because the first round would
    otherwise spend the whole budget on synonyms of the trade's own name and
    never reach the phrasings that do not mention it.
    """
    def article(word: str) -> str:
        return "an" if word[:1].lower() in "aeiou" else "a"

    def _is_a_person(name: str) -> bool:
        """"who does lawn care" is a question; "who does plumber" is not."""
        return name.rsplit(" ", 1)[-1].endswith(("er", "or", "ist", "ian", "smith"))

    rounds: list[list[str]] = []
    primary = names[0] if names else ""
    if primary:
        rounds.append([f"emergency {primary}"] if urgency == "emergency" else [])
        name_shapes = [s for s in ASK_SHAPES
                       if not (s.startswith("who does")
                               and _is_a_person(primary))]
        rounds.append([s.format(a=article(primary), name=primary)
                       for s in name_shapes])
    # The job in the customer's own words, before any second name for the trade.
    shapes = JOB_SHAPES if category in REPAIR_CATEGORIES else HELP_SHAPES
    rounds.append([s.format(thing=thing)
                   for thing in things[:3] for s in shapes[:2]])
    rounds.append(list(problems[:4]))
    for name in names[1:3]:
        rounds.append([s.format(a=article(name), name=name) for s in ASK_SHAPES[:4]])

    out, seen = [], set()
    for group in rounds:
        for phrase in group:
            phrase = " ".join(phrase.split())
            if phrase and phrase not in seen:
                seen.add(phrase)
                out.append(phrase)
    return out[:MAX_ASKS]


def quote(term: str) -> str:
    """YAML-safe, and readable in the file afterwards."""
    return '"' + term.replace('"', "'") + '"'


def render(row: dict, vocab: dict, also_shared: set[str] | None = None) -> str:
    """One profile, as the YAML a person can then edit by hand."""
    broad = set(vocab.get("broad") or ()) | set(also_shared or ())
    subject = [t for t in (vocab.get("subject") or []) if t not in broad]
    shared = [t for t in (vocab.get("subject") or []) if t in broad]
    problem = vocab.get("problem") or []
    name = row["display_name"]
    # What the customer calls the person they want. The display name and the
    # names people actually type -- "AC guy" finds posts "plumbing contractor"
    # never will.
    called = [name.lower()] + [a.lower() for a in row["also_called"]]
    called = list(dict.fromkeys(c for c in called if c))

    asks = ask_phrases(called, subject + shared, problem, row["urgency"],
                       row["category"])

    own_names = [c for c in called if c not in broad]
    shared_names = [c for c in called if c in broad]
    if not own_names:                    # every name it has is ambiguous
        own_names, shared_names = called[:1], shared_names[1:]

    lines = [
        MARKER,
        f"# rank {row['rank']} of 100 · {row['category']} · {row['frequency']} demand",
        "#",
        "# Hand edits are kept: regenerating skips any profile without the marker",
        "# above. Delete the marker to adopt this file as your own.",
        f"trade: {row['slug']}",
        f"display_name: {name}",
        "thresholds: {subject: 3, intent: 3}",
        f"recency_half_life_hours: {HALF_LIFE.get(row['urgency'], 48)}"
        f"   # {row['urgency']}",
        "",
        "subject:",
        f"  - terms: [{', '.join(quote(t) for t in own_names)}]",
        "    weight: 3",
        "    label: the-trade-itself",
    ]
    if subject:
        lines += [
            f"  - terms: [{', '.join(quote(t) for t in subject)}]",
            "    weight: 3",
            "    label: what-the-work-involves",
        ]
    shared = shared_names + shared
    if shared:
        # Words this trade shares with others: "garage", "range", "window".
        # Weighted below the threshold on purpose, so one of them can never make
        # a match by itself -- it can only support a term that already fits.
        # "Salary range 70-90k" matched an appliance repair profile on "range"
        # until this group existed.
        lines += [
            f"  - terms: [{', '.join(quote(t) for t in shared)}]",
            "    weight: 1",
            "    label: shared-with-other-trades",
        ]
    lines += ["", "intent:"]
    if problem:
        lines += [
            f"  - terms: [{', '.join(quote(t) for t in problem)}]",
            "    weight: 4",
            "    kind: problem",
            "    label: something-is-wrong",
        ]
    lines += [
        f"  - terms: [{', '.join(quote(a) for a in asks)}]",
        "    weight: 4",
        "    kind: request",
        "    label: asking-for-this-trade",
        "",
        "",
        "exclude:",
        f"  - terms: [{', '.join(quote(s.format(name=n)) for n in own_names[:2] for s in OFFER_SHAPES)}]",
        "    label: offering-this-service",
        "",
        "# The rest of the exclusions, and the shared asking language, come",
        "# from _defaults.yaml.",
        "",
        f"ask: [{', '.join(quote(a) for a in asks)}]",
        "",
        f"suggestions: [{', '.join(quote(t) for t in (subject or shared or called)[:8])}]",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build trade profiles from research")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--professions", default=str(RESEARCH / "PROFESSIONS-100.md"))
    ap.add_argument("--vocabulary", default=str(RESEARCH / "TRADE-VOCABULARY.md"))
    ap.add_argument("--out", default=str(PROFILES))
    ap.add_argument("--require-vocabulary", action="store_true",
                    help="skip any trade with no researched vocabulary, rather "
                         "than writing a profile that only knows its own name")
    args = ap.parse_args(argv)

    rows = professions(Path(args.professions))
    if not rows:
        print(f"no professions found in {args.professions}")
        return 1
    vocab = vocabulary(Path(args.vocabulary))
    out = Path(args.out)
    common = shared_terms(vocab, rows)
    by_hand = claimed_by_hand_written(out)
    # A word the hand-tuned profiles already claim needs only one more claimant.
    common |= {term for term in by_hand
               if sum([by_hand[term],
                       sum(1 for e in vocab.values()
                           if term in (e.get("subject") or []))]) >= SHARED_ACROSS}

    written, skipped, thin = 0, [], []
    for row in rows:
        have = vocab.get(row["slug"], {})
        if args.require_vocabulary and not have.get("subject"):
            thin.append(row["slug"])
            continue
        if not have.get("subject"):
            thin.append(row["slug"])
        existing = out / f"{ALIASES.get(row['slug'], row['slug'])}.yaml"
        if existing.exists() and MARKER not in existing.read_text(encoding="utf-8"):
            # Hand-written, and under its own name if this trade was aliased.
            skipped.append(f"{row['slug']} -> {existing.stem}"
                           if existing.stem != row["slug"] else row["slug"])
            continue
        target = out / f"{row['slug']}.yaml"
        body = render(row, have, common)
        if not args.dry_run:
            target.write_text(body, encoding="utf-8")
        written += 1

    print(f"{'would write' if args.dry_run else 'wrote'} {written} profiles "
          f"into {out}")
    if common:
        sample = ", ".join(sorted(common)[:10])
        print(f"{len(common)} terms are shared by {SHARED_ACROSS}+ trades and "
              f"cannot carry a match alone: {sample}"
              f"{' ...' if len(common) > 10 else ''}")
    if skipped:
        print(f"left alone (hand-edited): {', '.join(sorted(skipped))}")
    if thin:
        print(f"no researched vocabulary yet ({len(thin)}): "
              f"{', '.join(sorted(thin)[:12])}{' ...' if len(thin) > 12 else ''}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
